#!/bin/bash

set -e -x

mkdir -p "$T"/build-gcc
cd "$T"/build-gcc/

rm -f .have-build .have-install
if ! test -f .have-configure; then
  ("$T"/source-gcc/configure \
    --prefix= \
    --disable-bootstrap \
    --enable-languages=c,c++,fortran,lto \
    --disable-multilib \
    --enable-offload-targets=x86_64-intelmicemul-linux-gnu="$T"/install/offload-x86_64-intelmicemul-linux-gnu \
    --with-sysroot= &&
  touch .have-configure) 2>&1 | tee -a log_build
fi
test -f .have-configure
(make "$@" &&
touch .have-build) 2>&1 | tee -a log_build
test -f .have-build
